webtalk_init -webtalk_dir D:/Vivado/Lab2_Handouts_0406_2/Lab_BusControl_A/Lab_BusControl_A.sim/sim_1/behav/xsim/xsim.dir/topsim_link_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Apr 16 17:24:45 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "cbe6757e-807f-4c17-acf9-95e0056e3c34" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "54dd5debadab4e60971dad2691b0f1f9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "35" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1320 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6084_KB" -context "xsim\\usage"
webtalk_transmit -clientid 333562263 -regid "" -xml D:/Vivado/Lab2_Handouts_0406_2/Lab_BusControl_A/Lab_BusControl_A.sim/sim_1/behav/xsim/xsim.dir/topsim_link_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Vivado/Lab2_Handouts_0406_2/Lab_BusControl_A/Lab_BusControl_A.sim/sim_1/behav/xsim/xsim.dir/topsim_link_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Vivado/Lab2_Handouts_0406_2/Lab_BusControl_A/Lab_BusControl_A.sim/sim_1/behav/xsim/xsim.dir/topsim_link_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
