set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk]
set_property PACKAGE_PIN P17 [get_ports clk]
#从右到左
set_property PACKAGE_PIN P2 [get_ports hex0[0]]
set_property PACKAGE_PIN P3 [get_ports hex0[1]]
set_property PACKAGE_PIN P4 [get_ports hex0[2]]
set_property PACKAGE_PIN P5 [get_ports hex0[3]]


set_property PACKAGE_PIN R17 [get_ports x1]
set_property PACKAGE_PIN R15 [get_ports x2]
set_property PACKAGE_PIN V1 [get_ports x3]
set_property PACKAGE_PIN U4 [get_ports x4]
set_property PACKAGE_PIN R11 [get_ports x0]


#从右到左
set_property PACKAGE_PIN B4 [get_ports segs0[7]]
set_property PACKAGE_PIN A4 [get_ports segs0[6]]
set_property PACKAGE_PIN A3 [get_ports segs0[5]]
set_property PACKAGE_PIN B1 [get_ports segs0[4]]
set_property PACKAGE_PIN A1 [get_ports segs0[3]]
set_property PACKAGE_PIN B3 [get_ports segs0[2]]
set_property PACKAGE_PIN B2 [get_ports segs0[1]]
set_property PACKAGE_PIN D5 [get_ports segs0[0]]
set_property PACKAGE_PIN D4 [get_ports segs1[7]]
set_property PACKAGE_PIN E3 [get_ports segs1[6]]
set_property PACKAGE_PIN D3 [get_ports segs1[5]]
set_property PACKAGE_PIN F4 [get_ports segs1[4]]
set_property PACKAGE_PIN F3 [get_ports segs1[3]]
set_property PACKAGE_PIN E2 [get_ports segs1[2]]
set_property PACKAGE_PIN D2 [get_ports segs1[1]]
set_property PACKAGE_PIN H2 [get_ports segs1[0]]


set_property PACKAGE_PIN G2 [get_ports len[7]]
set_property PACKAGE_PIN C2 [get_ports len[6]]
set_property PACKAGE_PIN C1 [get_ports len[5]]
set_property PACKAGE_PIN H1 [get_ports len[4]]
set_property PACKAGE_PIN G1 [get_ports len[3]]
set_property PACKAGE_PIN F1 [get_ports len[2]]
set_property PACKAGE_PIN E1 [get_ports len[1]]
set_property PACKAGE_PIN G6 [get_ports len[0]]


set_property PACKAGE_PIN K3 [get_ports led[0]]
set_property PACKAGE_PIN M1 [get_ports led[1]]
set_property PACKAGE_PIN L1 [get_ports led[2]]
set_property PACKAGE_PIN K6 [get_ports led[3]]
set_property PACKAGE_PIN J5 [get_ports led[4]]
set_property PACKAGE_PIN H5 [get_ports led[5]]
set_property PACKAGE_PIN H6 [get_ports led[6]]
set_property PACKAGE_PIN K1 [get_ports led[7]]
set_property PACKAGE_PIN K2 [get_ports led[8]]
set_property PACKAGE_PIN J2 [get_ports led[9]]
set_property PACKAGE_PIN J3 [get_ports led[10]]
set_property PACKAGE_PIN H4 [get_ports led[11]]
set_property PACKAGE_PIN J4 [get_ports led[12]]
set_property PACKAGE_PIN G3 [get_ports led[13]]
set_property PACKAGE_PIN G4 [get_ports led[14]]
set_property PACKAGE_PIN F6 [get_ports led[15]]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports hex0[0]]
set_property IOSTANDARD LVCMOS33 [get_ports hex0[1]]
set_property IOSTANDARD LVCMOS33 [get_ports hex0[2]]
set_property IOSTANDARD LVCMOS33 [get_ports hex0[3]]
set_property IOSTANDARD LVCMOS33  [get_ports x1]
set_property IOSTANDARD LVCMOS33  [get_ports x2]
set_property IOSTANDARD LVCMOS33 [get_ports x3]
set_property IOSTANDARD LVCMOS33 [get_ports x4]
set_property IOSTANDARD LVCMOS33 [get_ports x0]
#从右到左
set_property IOSTANDARD LVCMOS33 [get_ports segs0[7]]
set_property IOSTANDARD LVCMOS33 [get_ports segs0[6]]
set_property IOSTANDARD LVCMOS33 [get_ports segs0[5]]
set_property IOSTANDARD LVCMOS33 [get_ports segs0[4]]
set_property IOSTANDARD LVCMOS33 [get_ports segs0[3]]
set_property IOSTANDARD LVCMOS33 [get_ports segs0[2]]
set_property IOSTANDARD LVCMOS33 [get_ports segs0[1]]
set_property IOSTANDARD LVCMOS33 [get_ports segs0[0]]
set_property IOSTANDARD LVCMOS33 [get_ports segs1[7]]
set_property IOSTANDARD LVCMOS33 [get_ports segs1[6]]
set_property IOSTANDARD LVCMOS33 [get_ports segs1[5]]
set_property IOSTANDARD LVCMOS33 [get_ports segs1[4]]
set_property IOSTANDARD LVCMOS33 [get_ports segs1[3]]
set_property IOSTANDARD LVCMOS33 [get_ports segs1[2]]
set_property IOSTANDARD LVCMOS33 [get_ports segs1[1]]
set_property IOSTANDARD LVCMOS33 [get_ports segs1[0]]
set_property IOSTANDARD LVCMOS33 [get_ports len[7]]
set_property IOSTANDARD LVCMOS33 [get_ports len[6]]
set_property IOSTANDARD LVCMOS33 [get_ports len[5]]
set_property IOSTANDARD LVCMOS33 [get_ports len[4]]
set_property IOSTANDARD LVCMOS33 [get_ports len[3]]
set_property IOSTANDARD LVCMOS33 [get_ports len[2]]
set_property IOSTANDARD LVCMOS33 [get_ports len[1]]
set_property IOSTANDARD LVCMOS33 [get_ports len[0]]
set_property IOSTANDARD LVCMOS33 [get_ports led[0]]
set_property IOSTANDARD LVCMOS33 [get_ports led[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led[4]]
set_property IOSTANDARD LVCMOS33 [get_ports led[5]]
set_property IOSTANDARD LVCMOS33 [get_ports led[6]]
set_property IOSTANDARD LVCMOS33 [get_ports led[7]]
set_property IOSTANDARD LVCMOS33 [get_ports led[8]]
set_property IOSTANDARD LVCMOS33 [get_ports led[9]]
set_property IOSTANDARD LVCMOS33 [get_ports led[10]]
set_property IOSTANDARD LVCMOS33 [get_ports led[11]]
set_property IOSTANDARD LVCMOS33 [get_ports led[12]]
set_property IOSTANDARD LVCMOS33 [get_ports led[13]]
set_property IOSTANDARD LVCMOS33 [get_ports led[14]]
set_property IOSTANDARD LVCMOS33 [get_ports led[15]]
